# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeReduxBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Firebase/Core', '~> 5.3.0'
  # Pods for ReactNativeReduxBoilerplate
	pod 'Firebase/Auth', '~> 5.3.0'
  target 'ReactNativeReduxBoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeReduxBoilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeReduxBoilerplate-tvOS

  target 'ReactNativeReduxBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
